### ISSUE TITLE
Adding support for OnlyEnforceIf and AddAssumptions

### ISSUE THREAD

**Issue by braindeaf** [ankane/or-tools#14]
would it be possible to add support for OnlyEnforceIf and AddAssumptions?

RobL

**Comment by ankane** [comment]
Added

**Comment by braindeaf** [comment]
Excellent, thank you :)

**Comment by braindeaf** [comment]
Ever seen this sucker before? I did let MacOSX upgrade the other day and command line tools were definitely not right afterwards.

Robs-MacBook-Pro:or-tools rl$ bundle exec rake test TEST=test/assumptions_sample_sat_test.rb 
Run options: --seed 3997

# Running:

dyld: lazy symbol binding failed: Symbol not found: __ZN19operations_research3sat14CpModelBuilder14AddAssumptionsEN4absl14lts_2020_09_234SpanIKNS0_7BoolVarEEE
  Referenced from: /Users/rl/repos/or-tools/lib/or_tools/ext.bundle
  Expected in: flat namespace

dyld: Symbol not found: __ZN19operations_research3sat14CpModelBuilder14AddAssumptionsEN4absl14lts_2020_09_234SpanIKNS0_7BoolVarEEE
  Referenced from: /Users/rl/repos/or-tools/lib/or_tools/ext.bundle
  Expected in: flat namespace

rake aborted!
SignalException: SIGABRT

**Comment by ankane** [comment]
Hmm, haven't seen that. Try `bundle exec rake clobber compile` to see if that fixes it.

**Comment by braindeaf** [comment]
solved. I had an outdated master branch for starters, needed to uninstall my or-tools installed by brew as well. 

Tried adding a test for assumptions but something isn't quite right, would it also be possilbe to add SufficientAssumptionsForInfeasibility ?

https://github.com/ankane/or-tools/pull/17

All the best

**Comment by ankane** [comment]
Added in 3e31da05b7873129cde5907daab7ddfc6acb83ab.

**Comment by braindeaf** [comment]
Thanks again.
