### ISSUE TITLE
Print model?

### ISSUE THREAD

**Issue by stevenshack** [ankane/or-tools#20]
In the or-tools c++ interface there is solver.ExportModelAsLpFormat to print out model details. This would be useful for debug purposes if it were exposed on ruby land. BTW thanks for the good work on this project.

**Comment by ankane** [comment]
Hey @stevenshack, thanks for the suggestion! Added in the commit above.

**Comment by stevenshack** [comment]
No problem. Is there an equivalent for VRP? I actually thought the VRP code was using a linear solver under the hood.

**Comment by ankane** [comment]
Not that I'm aware of. OR-Tools routing code uses the CP solver.
